### ISSUE TITLE
Mention the use of Scicrunch Registry identifiers for software

### ISSUE THREAD

**Issue by cthoyt** [egonw/compact-ids-in-reports#2]
Some journals require adding SciCrunch Registry identifiers for software, such as required by eLife. However, these are tangled up in the RRID system which sort of are compact IDs in spirit but not in syntax

e.g., `RRID:SCR_022476` appears in https://elifesciences.org/articles/72879, but the actual compact ID representation is `SCR:022476`

**Comment by egonw** [comment]
Thanks for the reminder! Added: https://github.com/egonw/compact-ids-in-reports/commit/d4d3dc5b0765f15df4be529ea610336e88c65567
