### ISSUE TITLE
`taxonomy:9606` is an iffy example

### ISSUE THREAD

**Issue by cthoyt** [egonw/compact-ids-in-reports#3]
It's really good to mention highly used namespaces, but the `taxonomy` prefix is a perfect example of how different communities reuse the same prefix to actually mean different things

Identifiers.org didn't do us a big favor in being non-specific with this one, and the Bioregistry tried to steer this on course by using `NCBITaxon` as the preferred prefix for this resource

I don't think that the target audience will appreciate this nuance in a short document, so i'd suggest using a different example

**Comment by larsgw** [comment]
Perhaps [`col:6MB3T`](http://identifiers.org/col:6MB3T)?

**Comment by egonw** [comment]
Thanks, applied.
